# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-10 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('addr', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
